### ISSUE TITLE
implement erlang monitors

### ISSUE THREAD

**Issue by moonpolysoft** [boundary/scalang#1]
Implement erlang monitors and upgrade the erlang distribution headers such that scalang nodes are no longer treated as special hidden nodes.

**Comment by maxnewbould** [comment]
Ill get right on it

On Jun 27, 2011 9:07 AM, "cliffmoon" <
reply@reply.github.com>
wrote:

Implement erlang monitors and upgrade the erlang distribution headers such
that scalang nodes are no longer treated as special hidden nodes.

## 

Reply to this email directly or view it on GitHub:
https://github.com/boundary/scalang/issues/1
